### ISSUE TITLE
Request feature

### ISSUE THREAD

**Issue by Thorbadin** [anysom/GridColumnCarousel#1]
Hi anysom,

First thx for the awesome script! I was tryuing to play with it to add a autoplay feature and a previous/next button to be able to navigate in the carousel. It is something easy to do? I see in your script were you append the element, I add a slide-x class to the li element but I can't go far this point. Thx in advance and again, great piece of code you made!

**Comment by anysom** [comment]
Hej Thorbadin

Thank you very much for your words! It means a lot to hear that you like it :) I will look into this issue in the weekend and hopefully be ready with an update for you. If you have any other feedback in the future just let me know.
Have a great Friday, I will let you know when the next version is out.

**Comment by anysom** [comment]
Hi again Thorbadin

I have implemented autoplay functionality. You can toggle it by setting an autoplay property to true in the options object you pass to the carousel. You can also specify the delay between each automatic slide change by setting the autoplayDelay property.

As for the next and prev arrows, I intentionally didn't implement them to begin with, as I think it is up to the user of this plugin to add these arrows where needed. I might implement some default arrows during the weekend though.. The script does however expose a method called slide that you can call to change slide. It takes one argument that can be either 'next', 'prev', 'first', 'last' or a number dictating the index of the slide you want to slide to. I would recommend using on of the keywords though as you cannot be sure what the indexes are as the breakpoints change.

I will update the documentation for the script ASAP, but I just wanted to let you know that there is a new version out now. You can check out how to use this functionality in the script in index.html.

Hope this sorts out your problem :)

**Comment by Thorbadin** [comment]
Hi again anysom,

SImply WOW! you're anwesome! That was exactly what I tought! I already made some change to my code be able to have the next and previous arrow with some jquery, but the autoplay seems really great! I'll try it right now.

Thx again for your wonderfull help :)
Have a nice day!

**Comment by anysom** [comment]
Hi again Thorbadin
Just found a bug where clicking the indicators would not change slide. I don't know if you are using them, but I just wanted to let you know that i fixed the issue.

Cheers

**Comment by Thorbadin** [comment]
Hi again anysome,

Thx for the fix :). Just to let you know the carousel is not working at all in safari (iphone, ipad, etc). Do you have any idea why?

thx in advance and have a nice day
