### ISSUE TITLE
Options Available

### ISSUE THREAD

**Issue by keithmclaughlin** [anysom/GridColumnCarousel#2]
Hi,

Thanks for this script.

Is there a way to tell it to only slide one column at a time? You mentioned there were settings for the options object but never specified what they were.

**Comment by anysom** [comment]
Hi Keith

Actually I was just in the middle of specifying these options and adding some new examples as you wrote.
Sliding only 1 column at a time is not supported as of now, but now that you have mentioned it, i might implement it in the future.
If you still need a list of the options, then i can ping you when i have updated the github page.

**Comment by anysom** [comment]
The options have been added to the github page http://anysom.github.io/GridColumnCarousel/
