### ISSUE TITLE
Safari device not working...

### ISSUE THREAD

**Issue by Thorbadin** [anysom/GridColumnCarousel#3]
Hi again anysome,

Just to let you know the carousel is not working at all in safari (iphone, ipad, etc). Do you have any idea why? PS I just saw I reply in a close ticket so that why I repost it here.

thx again and have a nice day

**Comment by anysom** [comment]
Hi again Thorbadin

I did see that you commented on the other open issue, but haven't had time to read it untill now.. And thank you very much for reporting this :) I guess I have been a bit to sluppy with the testing in the end.. I will look into it as soon as I have time, and notify you when its done.

Have a great monday :)

**Comment by anysom** [comment]
Fixed! woop woop :)

**Comment by Thorbadin** [comment]
Thx Anysom!! your awesome!! :)
