### ISSUE TITLE
GCCarousel is not defined after latest updated

### ISSUE THREAD

**Issue by Maculotti** [anysom/GridColumnCarousel#6]
That's all: GCCarousel is not defined after your latest updated before that everything works well.

**Comment by kampiamodikuesto** [comment]
i have same problem, GCCarousel aren't recognize.

**Comment by anysom** [comment]
Alright guys, it should be fixed now.. And sorry for the long wait I have been swamped lately... Oh and thank you very much for reporting this :D

**Comment by kampiamodikuesto** [comment]
Can you tell me what was the problem?
